CREATE SEQUENCE API_DATA_SEQ;

CREATE TABLE LZ_API_DATA (
    ID INTEGER NOT NULL DEFAULT NEXTVAL('API_DATA_SEQ'),
    API_DATA TEXT,
    DATA_SOURCE VARCHAR(100),
    SYS_INSERT_DATETIME TIMESTAMP
);
