

CREATE PROCEDURE SP_DIM_LOCATION_INSERT(
    _COUNTRY VARCHAR(100),
    _TIMEZONE INT,
    _ID INT,
    _LOC_NAME VARCHAR(100),
    _LON NUMERIC,
    _LAT NUMERIC,
    _API_ID NUMERIC,
	_SYS_INSERT_DATETIME TIMESTAMP
)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO DIM_LOCATION (
		COUNTRY,
		TIMEZONE,
		ID,
		LOC_NAME,
		LON,
		LAT,
	    API_ID,
		SYS_INSERT_DATETIME
)
SELECT
	_COUNTRY
	,_TIMEZONE
	,_ID
	,_LOC_NAME
	,_LON
	,_LAT
	,_API_ID
	,_SYS_INSERT_DATETIME
WHERE NOT EXISTS (
	SELECT 1
	FROM DIM_LOCATION
	WHERE COUNTRY = _COUNTRY
	AND TIMEZONE = _TIMEZONE
	AND ID = _ID
	AND LOC_NAME = _LOC_NAME
	AND TRUNC(LAT,2) = TRUNC(_LAT,2)
	AND TRUNC(LON,2) = TRUNC(_LON,2)
);
END
$$;


CREATE PROCEDURE SP_DIM_WEATHER_INSERT_V9 (
    _ID NUMERIC,
    _MAIN VARCHAR(20),
    _DESCR VARCHAR(60),
    _ICON VARCHAR(10),
    _API_ID NUMERIC,
    _SYS_INSERT_DATETIME TIMESTAMP,
    INOUT W_ID BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM DIM_WEATHER T
        WHERE T.MAIN = _MAIN
        AND T.DESCR = _DESCR
        AND T.ICON = _ICON
    )
    THEN
        DELETE FROM DIM_WEATHER WHERE MAIN = _MAIN AND DESCR = _DESCR AND ICON = _ICON;
    END IF;

    INSERT INTO DIM_WEATHER (
        ID,
        MAIN,
        DESCR,
        ICON,
        API_ID,
        SYS_INSERT_DATETIME
    )
    VALUES (
        _ID,
        _MAIN,
        _DESCR,
        _ICON,
        _API_ID,
        _SYS_INSERT_DATETIME
    )
    RETURNING ID INTO W_ID;
END;
$$;



CREATE PROCEDURE SP_FACT_MAIN_INSERT (
	_LOCATION_ID INT,
	_WEATHER_ID INT,
	_TEMP NUMERIC,
	_FEELS_LIKE NUMERIC,
	_TEMP_MIN NUMERIC,
	_TEMP_MAX NUMERIC,
	_PRESSURE NUMERIC,
	_HUMIDITY NUMERIC,
	_SEA_LEVEL NUMERIC,
	_GRND_LEVEL NUMERIC,
	_WIND_SPEED NUMERIC,
	_WIND_DEG NUMERIC,
	_WIND_GUST NUMERIC,
	_API_ID NUMERIC,
    _SYS_INSERT_DATETIME TIMESTAMP
)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO FACT_MAIN (
		LOCATION_ID
		,WEATHER_ID
		,TEMP
		,FEELS_LIKE
		,TEMP_MIN
		,TEMP_MAX
		,PRESSURE
		,HUMIDITY
		,SEA_LEVEL
		,GRND_LEVEL
		,WIND_SPEED
		,WIND_DEG
		,WIND_GUST
		,API_ID
		,SYS_INSERT_DATETIME
)
VALUES (
		_LOCATION_ID
		,_WEATHER_ID
		,_TEMP
		,_FEELS_LIKE
		,_TEMP_MIN
		,_TEMP_MAX
		,_PRESSURE
		,_HUMIDITY
		,_SEA_LEVEL
		,_GRND_LEVEL
		,_WIND_SPEED
		,_WIND_DEG
		,_WIND_GUST
		,_API_ID
		,_SYS_INSERT_DATETIME
);
END
$$;