CREATE TABLE MAIN (
    TEMP NUMERIC(3, 2),
    FEELS_LIKE NUMERIC(3, 2),
    TEMP_MIN NUMERIC(3, 2),
    TEMP_MAX NUMERIC(3, 2),
    PRESSURE NUMERIC(10, 2),
    HUMIDITY NUMERIC(4, 2),
    SEA_LEVEL NUMERIC(5, 2),
    GRND_LEVEL NUMERIC(5, 2)
);


CREATE TABLE LOCATION(
    LOCATION_ID INT PRIMARY_KEY,
    COUNTRY VARCHAR(100),
    TIMEZONE INT,
    ID INT,
    LOC_NAME VARCHAR(100),
    COD INT,
    LON NUMERIC(10, 10),
    LAT NUMERIC(10, 10)
);